
GET http://localhost:8888/api/users HTTP/1.1
content-type: application/application/json

###
POST http://localhost:8888/api/v1/users HTTP/1.1
content-type: application/application/json

{
    "name": "urif",
    "email": "urif@gmail.com",
    "password": "221997",
    "phone": "081529939012"
}

###

POST http://localhost:8888/api/auth/login HTTP/1.1
content-type: application/application/json

{
    "email": "urif@gmail.com",
    "password": "secret22"
}


###
POST http://localhost:8888/api/auth/register HTTP/1.1
content-type: application/json

{
    "name": "urif",
    "email": "urif@gmail.com",
    "password": "secret22"
}

###
POST http://localhost:8888/api/auth/forgot-password HTTP/1.1
content-type: application/json

{
  "email": "laksana.laksana.herlambang@gmail.com"
}

###
POST http://localhost:8888/api/auth/reset-password HTTP/1.1
content-type: application/json

{
  "email": "jack@gmail.com",
  "otp": 813916,
  "password": 12345678
}



###
DELETE http://localhost:8888/api/v1/users/2 HTTP/1.1

###
GET http://localhost:8888/api/products HTTP/1.1
content-type: application/application/json

###
GET http://localhost:8888/api/products/35/variants HTTP/1.1
content-type: application/json

###
GET http://localhost:8888/api/products/33/sizes HTTP/1.1
content-type: application/json

###
GET http://localhost:8888/api/products/1/discounts HTTP/1.1
content-type: application/application/json

###
GET http://localhost:8888/api/products/1/images HTTP/1.1
content-type: application/json

###
GET http://localhost:8888/api/products/recommended-products HTTP/1.1
content-type: application/application/json

###
GET http://localhost:8888/api/products HTTP/1.1
content-type: application/application/


###
POST http://localhost:8888/api/cart HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MywiZW1haWwiOiJ1cmlmQGdtYWlsLmNvbSIsImV4cCI6MTc3NTU4NjM4MSwiaWF0IjoxNzc1NDk5OTgxfQ.yvzq2jgQoZPF2ZG6uvwEVZ3tBU42W5J5Lh-v3IBvU_s

{
  "product_id": 10,
  "size_id": 4,
  "variant_id": 20,
  "quantity": 3
}

###
GET http://localhost:8888/api/cart/summary HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MywiZW1haWwiOiJ1cmlmQGdtYWlsLmNvbSIsImV4cCI6MTc3NTU4NjM4MSwiaWF0IjoxNzc1NDk5OTgxfQ.yvzq2jgQoZPF2ZG6uvwEVZ3tBU42W5J5Lh-v3IBvU_s


###
GET http://localhost:8888/api/cart HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MywiZW1haWwiOiJ1cmlmQGdtYWlsLmNvbSIsImV4cCI6MTc3NTU5MDY3OCwiaWF0IjoxNzc1NTA0Mjc4fQ.Xd1wIBwxQ_yjVAI5SgauZAGfjQqSEgrE0mW1GyELCbI

###
POST http://localhost:8888/api/orders HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MywiZW1haWwiOiJ1cmlmQGdtYWlsLmNvbSIsImV4cCI6MTc3NTU5MDY3OCwiaWF0IjoxNzc1NTA0Mjc4fQ.Xd1wIBwxQ_yjVAI5SgauZAGfjQqSEgrE0mW1GyELCbI

{
  "delivery_fee": 10000,
  "tax": 5000
}

###
GET http://localhost:8888/api/products/1/images HTTP/1.1
content-type: application/application/