
GET http://localhost:8888/admin/users HTTP/1.1
content-type: application/application/json

###

GET http://localhost:8888/api/v1/users/2 HTTP/1.1
content-type: application/application/json

###
POST http://localhost:8888/api/v1/users HTTP/1.1
content-type: application/application/json

{
    "name": "jaka",
    "email": "jakamakarim@gmail.com",
    "password": "221997",
    "phone": "081529939012"
}

###

POST http://localhost:8888/admin/auth/login HTTP/1.1
content-type: application/application/json

{
    "email": "jakamakarim222@gmail.com",
    "password": "secret"
}

###
DELETE http://localhost:8888/api/v1/users/2 HTTP/1.1

###
GET http://localhost:8888/api/v1/products HTTP/1.1
content-type: application/application/json
