
GET http://localhost:8888/admin/users HTTP/1.1
content-type: application/application/json

###
POST http://localhost:8888/api/v1/users HTTP/1.1
content-type: application/application/json

{
    "name": "jaka",
    "email": "jakamakarim@gmail.com",
    "password": "221997",
    "phone": "081529939012"
}

###

POST http://localhost:8888/admin/auth/login HTTP/1.1
content-type: application/application/json

{
    "email": "jakamakarim222@gmail.com",
    "password": "secret"
}


###
POST http://localhost:8888/admin/auth/register HTTP/1.1
content-type: application/json

{
    "name": "wildan",
    "email": "wildan222@gmail.com",
    "password": "secret22"
}

###
POST http://localhost:8888/admin/auth/forgot-password HTTP/1.1
content-type: application/json

{
  "email": "anton@gmail.com"
}

###
POST http://localhost:8888/admin/auth/reset-password HTTP/1.1
content-type: application/json

{
  "email": "jack@gmail.com",
  "otp": 813916,
  "password": 12345678
}



###
DELETE http://localhost:8888/api/v1/users/2 HTTP/1.1

###
GET http://localhost:8888/admin/products HTTP/1.1
content-type: application/application/json

###
GET http://localhost:8888/admin/products/35/variants HTTP/1.1
content-type: application/application/json

###
GET http://localhost:8888/admin/products/7/sizes HTTP/1.1
content-type: application/application/json

###
GET http://localhost:8888/admin/products/1/discounts HTTP/1.1
content-type: application/application/json

###
GET http://localhost:8888/admin/products/1/images HTTP/1.1
content-type: application/application/json

###
GET http://localhost:8888/admin/products/recommended-products HTTP/1.1
content-type: application/application/json

###
GET http://localhost:8888/admin/products HTTP/1.1
content-type: application/application/json